# Generated by Django 4.0.5 on 2022-06-03 18:16

import appdata.admin
import appdata.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(default='', verbose_name='Текст')),
                ('important', models.BooleanField(default=False, verbose_name='Важное дело')),
                ('public', models.BooleanField(default=False, verbose_name='Публичность')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_at', models.DateTimeField(default=appdata.admin.get_time_plus_day, verbose_name='Время завершения')),
                ('status', models.IntegerField(choices=[(1, 'Активная'), (0, 'Отложенная'), (2, 'Выполнено')], default=1, verbose_name='Статус')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Дело',
                'verbose_name_plural': 'Дела',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(default='', verbose_name='Текст')),
                ('important', models.BooleanField(default=False, verbose_name='Важное дело')),
                ('public', models.BooleanField(default=False, verbose_name='Публичность')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_at', models.DateTimeField(default=appdata.models.get_time_plus_day, verbose_name='Время завершения')),
                ('status', models.IntegerField(choices=[(1, 'Активная'), (0, 'Отложенная'), (2, 'Выполнено')], default=1, verbose_name='Статус')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Дело',
                'verbose_name_plural': 'Дела',
            },
        ),
    ]
